export var DESIGN = {
  color: {
    ink: "#17202a",
    muted: "#64748b",
    faint: "#f6f8fb",
    line: "#d9e2ec",
    accent: "#16869a",
    accentDark: "#0f6574",
    userBg: "#eef8fb",
    userBorder: "#bfe6ee",
    assistantBg: "#f8fafc",
    assistantBorder: "#dbe7ef",
    codeBg: "#162334",
    codeText: "#e5eef8",
    quoteBg: "#f3fbf9",
    quoteBorder: "#30aaa6"
  },
  font: {
    body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
    mono: '"SF Mono", Menlo, Monaco, Consolas, "Roboto Mono", monospace'
  }
};

export var IMAGE_THEME = {
  bg: { type: "gradient", colors: ["#fcfcfc", "#ffffff", "#f9fafb"] },
  font: {
    title: "Lora, Georgia, serif",
    body: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    mono: '"SF Mono", Menlo, Monaco, Consolas, monospace'
  },
  color: {
    ink: "#0f2c59",
    muted: "#475569",
    accent: "#0f6574",
    accentDark: "#0b4e5a",
    cardBgUser: "#f0f7f9",
    cardBorderUser: "#aad0d6",
    cardBgAssistant: "#ffffff",
    cardBorderAssistant: "#e2e8f0",
    codeBg: "#0f172a",
    codeText: "#f1f5f9",
    quoteBg: "#f8fafc",
    quoteBorder: "#0f6574",
    tagBgUser: "#dff5fa",
    tagBorderUser: "#aadce7",
    tagBgAssistant: "#f1f5f9",
    tagBorderAssistant: "#dbe7ef"
  }
};

export var EXPORT_THEMES = {
  default: {
    id: "default",
    name: "Default Minimalist",
    bg: { type: "solid", colors: ["#fbfdfe"] },
    font: {
      title: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      mono: '"SF Mono", Menlo, Monaco, Consolas, monospace'
    },
    color: {
      ink: "#17202a",
      muted: "#64748b",
      accent: "#16869a",
      accentDark: "#0f6574",
      cardBgUser: "#eef8fb",
      cardBorderUser: "#bfe6ee",
      cardBgAssistant: "#f8fafc",
      cardBorderAssistant: "#dbe7ef",
      codeBg: "#162334",
      codeText: "#e5eef8",
      quoteBg: "#f3fbf9",
      quoteBorder: "#30aaa6",
      tagBgUser: "#eef8fb",
      tagBorderUser: "#bfe6ee",
      tagBgAssistant: "#f8fafc",
      tagBorderAssistant: "#dbe7ef",
      line: "#d9e2ec"
    },
    word: {
      fontAscii: "Arial",
      fontEastAsia: "DengXian",
      colorTitle: "0F6574",
      colorText: "1A202C",
      colorMuted: "64748B",
      pageBg: "FBFDFE",
      metaBg: "EAF7FA",
      metaBorder: "BFE6EE",
      metaText: "0F6574",
      userBg: "EEF8FB",
      userBorder: "0F6574",
      assistantBg: "F8FAFC",
      assistantBorder: "94A3B8",
      inlineCodeBg: "EAF7FA",
      inlineCodeText: "0F6574",
      codeBg: "162334",
      codeText: "E5EEF8",
      codeBorder: "162334",
      codeLabel: "9FB3C8",
      quoteBg: "F3FBF9",
      quoteBorder: "30AAA6",
      tableHeaderBg: "EAF7FA",
      tableHeaderText: "0F6574",
      tableBorder: "D9E2EC",
      separatorColor: "D9E2EC"
    }
  },
  natural: {
    id: "natural",
    name: "Natural",
    bg: { type: "solid", colors: ["#ffffff"] },
    font: {
      title: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      mono: '"SF Mono", Menlo, Monaco, Consolas, monospace'
    },
    color: {
      ink: "#1f2937",
      muted: "#6b7280",
      accent: "#334155",
      accentDark: "#111827",
      cardBgUser: "transparent",
      cardBorderUser: "transparent",
      cardBgAssistant: "transparent",
      cardBorderAssistant: "transparent",
      codeBg: "#f3f4f6",
      codeText: "#111827",
      quoteBg: "#f8fafc",
      quoteBorder: "#94a3b8",
      tagBgUser: "#f3f4f6",
      tagBorderUser: "#e5e7eb",
      tagBgAssistant: "#f3f4f6",
      tagBorderAssistant: "#e5e7eb",
      tagTextUser: "#374151",
      tagTextAssistant: "#374151",
      shadow: "transparent",
      line: "#e5e7eb"
    },
    word: {
      fontAscii: "Arial",
      fontEastAsia: "DengXian",
      colorTitle: "111827",
      colorText: "1F2937",
      colorMuted: "6B7280",
      pageBg: "FFFFFF",
      metaBg: "FFFFFF",
      metaBorder: "E5E7EB",
      metaText: "4B5563",
      roleLabelBg: "FFFFFF",
      roleLabelBorder: "E5E7EB",
      roleUserColor: "374151",
      roleAssistantColor: "374151",
      userBg: "FFFFFF",
      userBorder: "E5E7EB",
      assistantBg: "FFFFFF",
      assistantBorder: "E5E7EB",
      inlineCodeBg: "F3F4F6",
      inlineCodeText: "1F2937",
      codeBg: "F3F4F6",
      codeText: "111827",
      codeBorder: "E5E7EB",
      codeLabel: "6B7280",
      quoteBg: "F8FAFC",
      quoteBorder: "94A3B8",
      tableHeaderBg: "F8FAFC",
      tableHeaderText: "1F2937",
      tableBorder: "E5E7EB",
      separatorColor: "E5E7EB"
    }
  },
  oxford: {
    id: "oxford",
    name: "Oxford Academic",
    bg: { type: "solid", colors: ["#fcfcfa"] },
    font: {
      title: "Lora, Georgia, serif",
      body: "Lora, Georgia, serif",
      mono: 'Courier New, monospace'
    },
    color: {
      ink: "#111b21",
      muted: "#5a6e72",
      accent: "#0f6574",
      accentDark: "#0b4e5a",
      cardBgUser: "#f0f6f6",
      cardBorderUser: "#aad0d6",
      cardBgAssistant: "#ffffff",
      cardBorderAssistant: "#e2e8f0",
      codeBg: "#1a2421",
      codeText: "#e2edea",
      quoteBg: "#f5faf8",
      quoteBorder: "#0f6574",
      tagBgUser: "#f0f6f6",
      tagBorderUser: "#aad0d6",
      tagBgAssistant: "#ffffff",
      tagBorderAssistant: "#e2e8f0",
      line: "#d1dedb"
    },
    word: {
      fontAscii: "Georgia",
      fontEastAsia: "Songti SC",
      colorTitle: "0F6574",
      colorText: "111B21",
      colorMuted: "5A6E72",
      pageBg: "FCFCFA",
      metaBg: "F0F6F6",
      metaBorder: "AAD0D6",
      metaText: "0B4E5A",
      userBg: "F0F6F6",
      userBorder: "0B4E5A",
      assistantBg: "FFFFFF",
      assistantBorder: "D1DEDB",
      inlineCodeBg: "EEF5F4",
      inlineCodeText: "0B4E5A",
      codeBg: "1A2421",
      codeText: "E2EDEA",
      codeBorder: "1A2421",
      codeLabel: "B8CAC6",
      quoteBg: "F5FAF8",
      quoteBorder: "0F6574",
      tableHeaderBg: "EEF5F4",
      tableHeaderText: "0B4E5A",
      tableBorder: "D1DEDB",
      separatorColor: "D1DEDB"
    }
  },
  mckinsey: {
    id: "mckinsey",
    name: "McKinsey Executive",
    bg: { type: "solid", colors: ["#f4f7fa"] },
    font: {
      title: '"Times New Roman", Times, serif',
      body: 'Arial, sans-serif',
      mono: 'Consolas, monospace'
    },
    color: {
      ink: "#05162e",
      muted: "#5c6f84",
      accent: "#002060",
      accentDark: "#001030",
      cardBgUser: "#e9eff5",
      cardBorderUser: "#b9cbdc",
      cardBgAssistant: "#ffffff",
      cardBorderAssistant: "#d2dfec",
      codeBg: "#0f1c2c",
      codeText: "#e6eef5",
      quoteBg: "#f0f4f8",
      quoteBorder: "#002060",
      tagBgUser: "#e9eff5",
      tagBorderUser: "#b9cbdc",
      tagBgAssistant: "#ffffff",
      tagBorderAssistant: "#d2dfec",
      line: "#cbd9e7"
    },
    word: {
      fontAscii: "Times New Roman",
      fontEastAsia: "SimSun",
      colorTitle: "002060",
      colorText: "05162E",
      colorMuted: "5C6F84",
      pageBg: "F4F7FA",
      metaBg: "E7EEF6",
      metaBorder: "B9CBDC",
      metaText: "002060",
      userBg: "E9EFF5",
      userBorder: "001030",
      assistantBg: "FFFFFF",
      assistantBorder: "CBD9E7",
      inlineCodeBg: "E7EEF6",
      inlineCodeText: "002060",
      codeBg: "0F1C2C",
      codeText: "E6EEF5",
      codeBorder: "0F1C2C",
      codeLabel: "AFC0D0",
      quoteBg: "F0F4F8",
      quoteBorder: "002060",
      tableHeaderBg: "E7EEF6",
      tableHeaderText: "002060",
      tableBorder: "CBD9E7",
      separatorColor: "CBD9E7"
    }
  },
  newsprint: {
    id: "newsprint",
    name: "Retro Newsprint",
    bg: { type: "solid", colors: ["#f6f0e8"] },
    font: {
      title: "Courier New, monospace",
      body: "Courier New, monospace",
      mono: "Courier New, monospace"
    },
    color: {
      ink: "#1c1917",
      muted: "#6f665d",
      accent: "#1c1917",
      accentDark: "#1c1917",
      cardBgUser: "#eee4d8",
      cardBorderUser: "#c4b8a8",
      cardBgAssistant: "#faf4ea",
      cardBorderAssistant: "#ded2c2",
      codeBg: "#292524",
      codeText: "#f5f5f4",
      quoteBg: "#fbf6ee",
      quoteBorder: "#1c1917",
      tagBgUser: "#eee4d8",
      tagBorderUser: "#c4b8a8",
      tagBgAssistant: "#faf4ea",
      tagBorderAssistant: "#ded2c2",
      shadow: "rgba(92, 64, 40, 0.05)",
      line: "#d7cbbb"
    },
    word: {
      fontAscii: "Courier New",
      fontEastAsia: "SimSun",
      colorTitle: "1C1917",
      colorText: "1C1917",
      colorMuted: "6F665D",
      pageBg: "F6F0E8",
      metaBg: "EEE4D8",
      metaBorder: "C4B8A8",
      metaText: "1C1917",
      userBg: "EEE4D8",
      userBorder: "1C1917",
      assistantBg: "FAF4EA",
      assistantBorder: "D7CBBB",
      inlineCodeBg: "EEE4D8",
      inlineCodeText: "1C1917",
      codeBg: "292524",
      codeText: "F5F5F4",
      codeBorder: "292524",
      codeLabel: "D6CCC0",
      quoteBg: "FBF6EE",
      quoteBorder: "1C1917",
      tableHeaderBg: "EEE4D8",
      tableHeaderText: "1C1917",
      tableBorder: "D7CBBB",
      separatorColor: "D7CBBB"
    }
  },
  aurora: {
    id: "aurora",
    name: "Modern Aurora Glass",
    bg: { type: "mesh", colors: ["#D4E4F7", "#E4D5F6", "#D3F3EE"] },
    font: {
      title: 'Outfit, Inter, -apple-system, sans-serif',
      body: 'Inter, -apple-system, sans-serif',
      mono: '"SF Mono", Menlo, monospace'
    },
    color: {
      ink: "#0f172a",
      muted: "#475569",
      accent: "#6366f1",
      accentDark: "#4f46e5",
      cardBgUser: "rgba(238, 248, 251, 0.75)",
      cardBorderUser: "rgba(180, 220, 230, 0.4)",
      cardBgAssistant: "rgba(255, 255, 255, 0.75)",
      cardBorderAssistant: "rgba(255, 255, 255, 0.4)",
      codeBg: "#0f172a",
      codeText: "#f1f5f9",
      quoteBg: "rgba(248, 250, 252, 0.6)",
      quoteBorder: "#6366f1",
      tagBgUser: "rgba(238, 248, 251, 0.75)",
      tagBorderUser: "rgba(180, 220, 230, 0.4)",
      tagBgAssistant: "rgba(255, 255, 255, 0.75)",
      tagBorderAssistant: "rgba(255, 255, 255, 0.4)",
      shadow: "rgba(15, 23, 42, 0.08)",
      line: "rgba(226, 232, 240, 0.6)"
    },
    word: {
      fontAscii: "Arial",
      fontEastAsia: "DengXian",
      colorTitle: "4F46E5",
      colorText: "0F172A",
      colorMuted: "475569",
      pageBg: "F6F7FF",
      metaBg: "ECEEFD",
      metaBorder: "C7D2FE",
      metaText: "4338CA",
      userBg: "EEF2FF",
      userBorder: "6366F1",
      assistantBg: "FFFFFF",
      assistantBorder: "D7DAF8",
      inlineCodeBg: "ECEEFD",
      inlineCodeText: "4338CA",
      codeBg: "0F172A",
      codeText: "F1F5F9",
      codeBorder: "312E81",
      codeLabel: "C7D2FE",
      quoteBg: "F4F1FF",
      quoteBorder: "6366F1",
      tableHeaderBg: "ECEEFD",
      tableHeaderText: "4338CA",
      tableBorder: "D7DAF8",
      separatorColor: "D7DAF8"
    }
  },
  terminal: {
    id: "terminal",
    name: "Cyber Terminal",
    bg: { type: "gradient", colors: ["#f7fbf4", "#edf7ee", "#f9fbf5"] },
    font: {
      title: '"JetBrains Mono", Menlo, monospace',
      body: '"JetBrains Mono", Menlo, monospace',
      mono: '"JetBrains Mono", Menlo, monospace'
    },
    color: {
      ink: "#102018",
      muted: "#52645a",
      accent: "#2f7d4f",
      accentDark: "#14532d",
      cardBgUser: "#e5f3ea",
      cardBorderUser: "#9dccaf",
      cardBgAssistant: "#ffffff",
      cardBorderAssistant: "#d5e5da",
      codeBg: "#102016",
      codeText: "#d7ffe2",
      quoteBg: "#eef8f2",
      quoteBorder: "#2f7d4f",
      tagBgUser: "#dcf3e6",
      tagBorderUser: "#9dccaf",
      tagBgAssistant: "#ffffff",
      tagBorderAssistant: "#d5e5da",
      tagTextUser: "#14532d",
      tagTextAssistant: "#52645a",
      shadow: "rgba(21, 80, 46, 0.08)",
      line: "#cfe0d4"
    },
    word: {
      fontAscii: "Consolas",
      fontEastAsia: "DengXian",
      colorTitle: "14532D",
      colorText: "102018",
      colorMuted: "52645A",
      pageBg: "F7FBF4",
      metaBg: "E5F3EA",
      metaBorder: "9DCCAF",
      metaText: "14532D",
      userBg: "E5F3EA",
      userBorder: "2F7D4F",
      assistantBg: "FFFFFF",
      assistantBorder: "CFE0D4",
      inlineCodeBg: "E5F3EA",
      inlineCodeText: "14532D",
      codeBg: "102016",
      codeText: "D7FFE2",
      codeBorder: "102016",
      codeLabel: "92C7A4",
      quoteBg: "EEF8F2",
      quoteBorder: "2F7D4F",
      tableHeaderBg: "E5F3EA",
      tableHeaderText: "14532D",
      tableBorder: "CFE0D4",
      separatorColor: "CFE0D4"
    }
  },
  editorial: {
    id: "editorial",
    name: "Classic Editorial",
    bg: { type: "solid", colors: ["#faf8f5"] },
    font: {
      title: "Georgia, serif",
      body: "Georgia, serif",
      mono: 'Courier New, monospace'
    },
    color: {
      ink: "#1c1917",
      muted: "#78716c",
      accent: "#7c2d12",
      accentDark: "#431407",
      cardBgUser: "#f5f0eb",
      cardBorderUser: "#e7e5e4",
      cardBgAssistant: "#f1ede7",
      cardBorderAssistant: "#e7e5e4",
      codeBg: "#f5f5f4",
      codeText: "#1c1917",
      quoteBg: "#f5f5f4",
      quoteBorder: "#7c2d12",
      tagBgUser: "#f5f0eb",
      tagBorderUser: "#e7e5e4",
      tagTextUser: "#7c2d12",
      tagBgAssistant: "#f1ede7",
      tagBorderAssistant: "#e7e5e4",
      tagTextAssistant: "#5f5148",
      shadow: "transparent",
      line: "#e7e5e4"
    },
    word: {
      fontAscii: "Georgia",
      fontEastAsia: "KaiTi",
      colorTitle: "7C2D12",
      colorText: "1C1917",
      colorMuted: "78716C",
      pageBg: "FAF8F5",
      metaBg: "F1EDE8",
      metaBorder: "D8D0C7",
      metaText: "7C2D12",
      roleLabelBg: "F1EDE8",
      roleLabelBorder: "CDBFB4",
      roleUserColor: "7C2D12",
      roleAssistantColor: "5F5148",
      userBg: "F7F2ED",
      userBorder: "D8D0C7",
      assistantBg: "FFFDFC",
      assistantBorder: "E7E5E4",
      inlineCodeBg: "F1EDE8",
      inlineCodeText: "7C2D12",
      codeBg: "F1EDE8",
      codeText: "1C1917",
      codeBorder: "D8D0C7",
      codeLabel: "7C2D12",
      quoteBg: "F3EFEB",
      quoteBorder: "7C2D12",
      tableHeaderBg: "F1EDE8",
      tableHeaderText: "7C2D12",
      tableBorder: "D8D0C7",
      separatorColor: "D8D0C7"
    }
  },
  midnight: {
    id: "midnight",
    name: "Midnight Dark",
    bg: { type: "solid", colors: ["#181818"] },
    font: {
      title: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      body: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "PingFang SC", "Microsoft YaHei", sans-serif',
      mono: '"SF Mono", Menlo, Monaco, Consolas, monospace'
    },
    color: {
      ink: "#e3e3e3",
      muted: "#8e8e8e",
      accent: "#64d2ff",
      accentDark: "#54b3d6",
      cardBgUser: "#2a2b2d",
      cardBorderUser: "#4a4a4c",
      cardBgAssistant: "#252528",
      cardBorderAssistant: "#3d3d40",
      codeBg: "#2d2d30",
      codeText: "#e3e3e3",
      quoteBg: "#2d2d30",
      quoteBorder: "#64d2ff",
      tagBgUser: "#2a2b2d",
      tagBorderUser: "#4a4a4c",
      tagTextUser: "#ffffff",
      tagBgAssistant: "#2d2d30",
      tagBorderAssistant: "#3d3d40",
      tagTextAssistant: "#ffffff",
      shadow: "transparent",
      line: "#3d3d40"
    },
    word: {
      fontAscii: "Arial",
      fontEastAsia: "DengXian",
      colorTitle: "54B3D6",
      colorText: "E3E3E3",
      colorMuted: "8E8E93",
      pageBg: "181818",
      titleBg: "2A2B2D",
      titleBorder: "3A3A3C",
      metaBg: "2A2B2D",
      metaBorder: "3A3A3C",
      metaText: "8E8E93",
      roleLabelBg: "2A2B2D",
      roleLabelBorder: "3A3A3C",
      roleUserColor: "54B3D6",
      roleAssistantColor: "8E8E93",
      userBg: "2A2B2D",
      userBorder: "3A3A3C",
      assistantBg: "1F1F1F",
      assistantBorder: "2D2D30",
      inlineCodeBg: "2D2D30",
      inlineCodeText: "54B3D6",
      codeBg: "151A21",
      codeText: "E8EDF2",
      codeBorder: "3B4650",
      codeLabel: "6E6E73",
      quoteBg: "242426",
      quoteBorder: "54B3D6",
      tableHeaderBg: "2A2B2D",
      tableHeaderText: "E3E3E3",
      tableBorder: "2D2D30",
      separatorColor: "2D2D30"
    }
  }
};

export function getExportTheme(styleId) {
  return EXPORT_THEMES[styleId] || EXPORT_THEMES.default;
}
